-- DDL generated by Postico 1.5.10
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE fooditems (
    id SERIAL PRIMARY KEY,
    name text,
    unit text DEFAULT 'grams'::text,
    quantity double precision DEFAULT '0'::double precision,
    calories double precision DEFAULT '0'::double precision,
    protein_grams double precision DEFAULT '0'::double precision,
    carb_grams double precision DEFAULT '0'::double precision,
    fat_grams double precision DEFAULT '0'::double precision
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX fooditems_pkey ON fooditems(id int4_ops);
